### ISSUE TITLE
Unnecessary document.write in template

### ISSUE THREAD

**Issue by martinogden** [martinogden/django-banner-rotator#2]
Is there any reason for using javascript to generate the random number and write the banner swf / img to page. Can this not just be flat html?

**Comment by plazix** [comment]
This is made to protect against cache, although in this case, a random number probably is not necessary, because  hardly when updating a banner the file name will coincide. Now, I would have made the generation of unique file name (for example, the hash file name and timestamp) and would have removed from the javascript code.

**Comment by plazix** [comment]
version without javascript

https://github.com/plazix/django-banner-rotator/commit/6786340316ba81c675ff5b18ef628460d908f6f0

**Comment by martinogden** [comment]
Fixed in commit above ^^
